default: &default
  adapter: mysql2
  encoding: utf8
  pool: 20
  password: mypassword

development:
  <<: *default
  database: core_dev
  username: root
  host: 127.0.0.1

test:
  <<: *default
  username: root
  database: core_test
  host: 127.0.0.1
